// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Organizations.Infrastructure.Persistence;

#nullable disable

namespace Organizations.Infrastructure.Migrations.Postgresql
{
    [DbContext(typeof(OrganizationsDatabaseContext))]
    [Migration("20231229123308_AddSearchInfo")]
    partial class AddSearchInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Organizations.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_organizations_owner_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Organizations.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.OwnsOne("Organizations.Domain.ValueObjects.OrganizationSearchInfo", "SearchInfo", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("search_info_name");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.Navigation("SearchInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
